# Generated by Django 3.1 on 2021-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210516_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_brothers_unmarried',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_sisters_unmarried',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
